image: Visual Studio 2017
configuration: Release
version: 1.{build}

# build config
build_script:
  - nuget.exe pack -Version %APPVEYOR_BUILD_VERSION% -OutputDirectory .\artifacts

# artifacts config
artifacts:
  - path: '.\artifacts\*.nupkg'

deploy: off

for:
-  
  branches:
    only:
       - master

  deploy:
    - provider: NuGet
      api_key: 
        secure: z44CwwunvCyTy8Rk0BplABnNnahqkpfnS/rbHLo2uFrvFhQ7QvsR5mKkceqM/qou

-
  branches:
    only: 
      - dev

  deploy:
    - provider: NuGet
      server: https://www.myget.org/F/codestellation/api/v2/package
      api_key: 
        secure: sJ2aZzbtBoHsDlBJ7A7D62AVhDtXKZqWt30LWICqgpzALm0bEIGl96SfLg+Uoa3o